server:
  port: 5010
  domain: 0.0.0.0
  secret: vxkZtiGx83a77x3aUZJ8hy3h8YITUBPfHPkqtsR4/U0rUWfUSGe77g==

debug: true
timezone: america/los_angeles
database: main

authorization:
  username: ahslibrary
  password: ausdk12
